CREATE DATABASE IF NOT EXISTS ZenlessZoneZero;

USE ZenlessZoneZero;

CREATE TABLE IF NOT EXISTS `PERSONNAGE` (
    `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(255) NOT NULL,
    `element` VARCHAR(100) NOT NULL,
    `unitclass` VARCHAR(100) NOT NULL,
    `origin` VARCHAR(255) DEFAULT NULL,
    `rarity` INT NOT NULL,
    `url_img` VARCHAR(512) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;