CREATE DATABASE IF NOT EXISTS ZenlessZoneZero;
USE ZenlessZoneZero;


-- TABLE : ELEMENT
CREATE TABLE IF NOT EXISTS element (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    url_img VARCHAR(512) NOT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


-- TABLE : ORIGIN
CREATE TABLE IF NOT EXISTS origin (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    url_img VARCHAR(512) NOT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


-- TABLE : UNITCLASS
CREATE TABLE IF NOT EXISTS unitclass (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    url_img VARCHAR(512) NOT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


-- TABLE : PERSONNAGE
CREATE TABLE IF NOT EXISTS personnage (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    element INT NOT NULL,
    unitclass INT NOT NULL,
    origin INT DEFAULT NULL,
    rarity INT NOT NULL,
    url_img VARCHAR(512) NOT NULL,

    CONSTRAINT fk_personnage_element
    FOREIGN KEY (element) REFERENCES element(id)
    ON UPDATE CASCADE ON DELETE CASCADE,

    CONSTRAINT fk_personnage_unitclass
    FOREIGN KEY (unitclass) REFERENCES unitclass(id)
    ON UPDATE CASCADE ON DELETE CASCADE,

    CONSTRAINT fk_personnage_origin
    FOREIGN KEY (origin) REFERENCES origin(id)
    ON UPDATE CASCADE ON DELETE CASCADE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
4 COLLATE=utf8mb4_general_ci;